extends:
  - "prettier"
parserOptions:
  sourceType: "module"
plugins:
  - "prettier"
  - "html"
  - "vue"
  - "import"
settings:
  "import/resolver": "webpack"
env:
  "browser": true
  "node": true
rules:
   "indent":
    - "error"
    - 4
