#!/bin/bash

files=(
  .eslintrc.yaml
  .htmlhintrc.yaml
  .prettierrc.yaml
  .stylelintrc.yaml
)
dir_to_link=$HOME
dir_cur=$(pwd)

for file in "${files[@]}"
do
  ln -sf $dir_cur/$file $dir_to_link/$file
  echo "linked $file in $dir_to_link"
done
